---
title: "select neighbor + Zscore + mean squared diff"
output: html_document 
---

#updated pearson weight function -- for user * website matrix

```{r}
#a, u are users, df is user * website matrix
#pearson sim weight
load("../Data/train1.RData")
load("../Data/test1.RData")

weight = function(a,u, df) {

  r_a = df[a, ]
  r_u = df[u, ] 
  
  r_a_mean = mean(r_a)
  r_a_sd = sd(r_a)
  r_u_mean = mean(r_u)
  r_u_sd = sd(r_u)
  
  # i is the id of movie, a and u are id of users
  
  w_au = sum((r_a - r_a_mean) %*% (r_u - r_u_mean)) / r_a_sd * r_u_sd
  return(w_au)
}


```

# Variance weighting: based on pearson

```{r}
variance_weight = function(a,u,df) {

  # i is the id of movie, a and u are id of users
  r_a = df[a, ]
  r_u = df[u, ] 
  
  r_a_mean = mean(r_a)
  r_a_sd = sd(r_a)
  r_u_mean = mean(r_u)
  r_u_sd = sd(r_u)
  
 
  n <- ncol(df)
  
  var <- vector()
  for(i in 1:n) {
  var[i] <- sum((df[, i]-mean(df[,i]))^2)/(length(df[,i]) - 1)
  }
  var_min <- min(var)
  var_max <- max(var)
  
  v_i <- vector()
  for(i in 1:n) {
  v_i[i] <- (sum((df[, i]-mean(df[,i]))^2)/(length(df[,i]) - 1) - var_min) / var_max
  }
  #var_i <- sum((df[, i]-mean(df[,i]))^2)/(length(df[,i]) - 1)
  #v_i <- (var_i - var_min) / var_max

  w_au = sum((r_a - r_a_mean) %*% (r_u - r_u_mean) %*% v_i) / sum(v_i)
  return(w_au)

}
```

#Best-n-estimator

```{r}
#df is a user * website matrix, n is the number of neighbors selected
#run refer to which weighting methods we choose:
#1: pearson, 2: Spearman Correlation  
#3: variance weight 4: significance weight

selectNeighbor <- function(df, n, run){
  users <- rownames(df)
  m <- length(users)
  weights <- matrix(rep(NA, m * m), m, m)
  weights <- data.frame(weights)
  colnames(weights) <- users
  rownames(weights) <- users
  neighbors <- matrix(rep(NA, m * n), m, n)
  neighbors <- data.frame(neighbors)
  rownames(neighbors) <- users
  
  for (i in 1:m){
    for (j in 1:m){
      if (run == 1) weights[i,j] <- weight(users[i], users[j], df)
      #else if (run == 2) weights[i,j] <- 
      else if (run == 3) weights[i, j] <- variance_weight(users[i], users[j], df)
      #else if (run == 4) weights[i, j] <- 
    }
    neighbors[i, ] <- colnames(weights)[order(weights[i, ], decreasing=TRUE)][1:n]
  }
  r <- list(weightMatrix = weights, selectedNeighbors = neighbors)
  return (r)
}


```

#Mean-square-difference

```{r}


meanSquareDiff <- function(df){
  m <- dim(df)[1] #user number
  dissim <- matrix(rep(NA, m * m), m, m)
  dissim <- data.frame(dissim)
  users <- rownames(df)
  colnames(dissim) <- users
  rownames(dissim) <- users
  for (i in 1:m){
    for (j in 1:m){
      r_i <- df[i,]
      r_j <- df[j,]
      dissim[i, j] <- sum((r_i - r_j)^2)
    }
  }
  maxDissim <- max(dissim)
  sim <- (maxDissim - dissim)/maxDissim
  return (sim)
  
}

```

#select neighbors with weights matrix

```{r}
#used with weights matrix: MSD and simrank
selectNeighborWeights <- function(df, weights, n){
  users <- rownames(df)
  m <- length(users)
  neighbors <- matrix(rep(NA, m * n), m, n)
  neighors <- data.frame(neighbors)
  rownames(neighbors) <- users
  
  for (i in 1:m){
    neighbors[i, ] <- colnames(weights)[order(weights[i, ], decreasing=TRUE)][1:n]
  }
  return (neighbors)
}

```


#Z-score

```{r}
#a is the predicted user, i is the website id
computeZScore <- function(weights, neighbors, df, a, i){
  neighbors_a <- neighbors[toString(a), ] 
  num <- rep(0, length(neighbors_a))
  for (u in 1:length(neighbors_a)){
    neighborU <- neighbors_a[u] 
    r_ui <- df[toString(neighborU), toString(i)]
    r_u <- mean(df[neighborU, ])
    sd_u <- sd(df[neighborU, ])
    w_au <- weights[toString(a), neighborU]
    num[u] <- (r_ui - r_u)/sd_u * w_au
  }
  w_a <- sum(weights[toString(a), neighbors_a])
  sd_a <- sd(df[toString(a), ])
  index_not_i <- rownames(df) != i
  r_a <- mean(df[toString(a), index_not_i])
  p_ai <- r_a + sd_a * sum(num)/w_a
  return (p_ai)
}


```    


#prediction matrix

```{r}
pred <- function(weights, neighbors, df){
  a <- dim(df)[1]
  b <- dim(df)[2]
  users <- rownames(df)
  website <- colnames(df)
  predMatrix <- matrix(rep(NA, a * b), a, b)
  for (i in 1:a){
    for (j in 1:b){
      predMatrix[i, j] <- computeZScore(weights, neighbors, df, users[i], website[j])
    }
  }
}
```

df <- test1[1:100, ]

#step1: pearson weight + best-n + z-score

```{r}
x <- selectNeighbor(train1, 20, 1)
weights_pearson1 <- x[[1]]
neighbors_pearson1 <- x[[2]]

pred_pearson <- pred(weights_pearson1, neighbors_pearson1, train1)

```

#step2: 




