---
title: "select neighbor + Zscore + mean squared diff"
output: html_document 
---

#updated weight function -- for user * website matrix

```{r}
#a, u are users, df is user * website matrix
#spearman sim weight
weight = function(a,u, df) {

  rank_a = df[a, ]
  rank_u = df[u, ] 
  
  rank_a_mean = mean(rank_a)
  rank_a_sd = sd(rank_a)
  rank_u_mean = mean(rank_u)
  rank_u_sd = sd(rank_u)
  
  # i is the id of movie, a and u are id of users
  
  w_au = sum((rank_a - rank_a_mean) %*% (rank_u - rank_u_mean)) / rank_a_sd * rank_u_sd
  return(w_au)
}

weight("10001", "10003", test1[[2]])
weight("10001", "10001", test1[[2]])
```



#Best-n-estimator

```{r}
#df is a user * website matrix, n is the number of neighbors selected
selectNeighbor <- function(df, n){
  users <- rownames(df)
  m <- length(users)
  weights <- matrix(rep(NA, m * m), m, m)
  weights <- data.frame(weights)
  colnames(weights) <- users
  rownames(weights) <- users
  neighbors <- matrix(rep(NA, m * n), m, n)
  neighors <- data.frame(neighbors)
  rownames(neighbors) <- users
  
  for (i in 1:m){
    for (j in 1:m){
      weights[i,j] <- weight(users[i], users[j], df)
    }
    neighbors[i, ] <- colnames(weights)[order(weights[i, ], decreasing=TRUE)][1:n]
  }
  r <- list(weightMatrix = weights, selectedNeighbors = neighbors)
  return (r)
}

x <- selectNeighbor(test1[[2]], 20)
x[[1]]
x[[2]]

df <- train1[[2]][1:100, ]
df

df[1, -1]

y <- selectNeighbor(df, 20)
y[[1]]
y[[2]]
```

#Mean-square-di???erence

```{r}

sum((df[2,]-df[8,])^2)

meanSquareDiff <- function(df){
  m <- dim(df)[1] #user number
  dissim <- matrix(rep(NA, m * m), m, m)
  dissim <- data.frame(dissim)
  users <- rownames(df)
  colnames(dissim) <- users
  rownames(dissim) <- users
  for (i in 1:m){
    for (j in 1:m){
      r_i <- df[i,]
      r_j <- df[j,]
      dissim[i, j] <- sum((r_i - r_j)^2)
    }
  }
  maxDissim <- max(dissim)
  sim <- (maxDissim - dissim)/maxDissim
  return (sim)
  
}

meanSquareDiff(df)

selectNeighborMSD <- function(df, n){
  users <- rownames(df)
  m <- length(users)
  weights <- meanSquareDiff(df)
  neighbors <- matrix(rep(NA, m * n), m, n)
  neighors <- data.frame(neighbors)
  rownames(neighbors) <- users
  
  for (i in 1:m){
    neighbors[i, ] <- colnames(weights)[order(weights[i, ], decreasing=TRUE)][1:n]
  }
  r <- list(weightMatrix = weights, selectedNeighbors = neighbors)
  return (r)
}

z <- selectNeighborMSD(df, 20)
```


#Z-score

```{r}
#a is the predicted user, i is the website id
computeZScore <- function(weights, neighbors, df, a, i){
  neighbors_a <- neighbors[toString(a), ] 
  num <- rep(0, length(neighbors_a))
  for (u in 1:length(neighbors_a)){
    neighborU <- neighbors_a[u] 
    r_ui <- df[toString(neighborU), toString(i)]
    r_u <- mean(df[neighborU, ])
    sd_u <- sd(df[neighborU, ])
    w_au <- weights[toString(a), neighborU]
    num[u] <- (r_ui - r_u)/sd_u * w_au
  }
  w_a <- sum(weights[toString(a), neighbors_a])
  sd_a <- sd(df[toString(a), ])
  index_not_i <- rownames(df) != i
  r_a <- mean(df[toString(a), index_not_i])
  p_ai <- r_a + sd_a * sum(num)/w_a
  return (p_ai)
}

computeZScore(y[[1]], y[[2]], df, "10001", "1288") #spearman
computeZScore(z[[1]], z[[2]], df, "10001", "1288") #MSD
```




